version: '3'

services:
  # SET UP MYSQL
  mysql:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=geometrydash
    volumes:
      - db-data:/mysql
    ports:
      - "3306:3306"

  # SET UP WEB SERVER
  web:
    build: .
    ports:
      - "80:80"
    depends_on:
      - mysql

  # SET UP PHPMYADMIN
  pma:
    image: phpmyadmin
    ports:
      - "8080:80"

volumes:
  db-data:
